'use client'

import { RouteGuard } from '@/components/auth/route-guard'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { ServerCrash, AlertTriangle, CheckCircle, Smartphone, WifiOff, Globe, Database } from 'lucide-react'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'

const MOCK_LOGS = [
  { id: '1', system: 'PAYMENT_GATEWAY', endpoint: 'stripe.com/v1/charges', status: 402, time: '2 mins ago', msg: 'Card Declined: Insufficient Funds' },
  { id: '2', system: 'API_GATEWAY', endpoint: '/api/v1/orders', status: 429, time: '15 mins ago', msg: 'Rate Limit Exceeded: Zomato Integrator' },
  { id: '3', system: 'WEBHOOK', endpoint: 'whatsapp.api.meta.com', status: 500, time: '1 hour ago', msg: 'Internal Server Error' },
]

export default function EnterpriseMonitoring() {
  return (
    <RouteGuard module="analytics">
      <div className="flex flex-col gap-6">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-white">Enterprise Monitoring</h1>
          <p className="text-slate-500 dark:text-slate-400 mt-1">
            Real-time health of API Gateways, Integrations, and Offline Devices.
          </p>
        </div>

        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">API Gateway Health</CardTitle>
              <CheckCircle className="h-4 w-4 text-green-500" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-green-600 dark:text-green-400">99.99%</div>
              <p className="text-xs text-green-500/80">Uptime today</p>
            </CardContent>
          </Card>
          
          <Card className="border-amber-200 dark:border-amber-900/50 bg-amber-50/30 dark:bg-amber-950/20">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-amber-600 dark:text-amber-400">Offline POS Devices</CardTitle>
              <WifiOff className="h-4 w-4 text-amber-500" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-amber-600 dark:text-amber-400">2</div>
              <p className="text-xs text-amber-500/80">Outlets disconnected</p>
            </CardContent>
          </Card>
          
          <Card className="border-red-200 dark:border-red-900/50 bg-red-50/30 dark:bg-red-950/20">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-red-600 dark:text-red-400">Failed Webhooks</CardTitle>
              <AlertTriangle className="h-4 w-4 text-red-500" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-red-600 dark:text-red-400">14</div>
              <p className="text-xs text-red-500/80">Requires replay</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Failed Sync Events</CardTitle>
              <Database className="h-4 w-4 text-slate-500" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-slate-900 dark:text-white">0</div>
              <p className="text-xs text-slate-500">All local databases synced</p>
            </CardContent>
          </Card>
        </div>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><ServerCrash className="h-5 w-5 text-red-500" /> Integration Error Log</CardTitle>
            <CardDescription>Live feed of errors generated by the API Gateway and external integrations.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="border rounded-lg overflow-hidden dark:border-slate-800">
              <Table>
                <TableHeader className="bg-slate-50 dark:bg-slate-900">
                  <TableRow>
                    <TableHead>Timestamp</TableHead>
                    <TableHead>System</TableHead>
                    <TableHead>Endpoint</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Error Message</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {MOCK_LOGS.map(log => (
                    <TableRow key={log.id}>
                      <TableCell className="text-xs text-slate-500">{log.time}</TableCell>
                      <TableCell className="font-bold text-xs">{log.system.replace('_', ' ')}</TableCell>
                      <TableCell className="font-mono text-xs">{log.endpoint}</TableCell>
                      <TableCell>
                        <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-bold bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400">
                          {log.status}
                        </span>
                      </TableCell>
                      <TableCell className="text-sm">{log.msg}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>
      </div>
    </RouteGuard>
  )
}
